sudo: required

language: generic

services: -docker

before_install: -echo "start creating an image with dockerfile0"
  -docker build -t ksh931101/docker-react-app -f Dockerfile.dev .

script: -docker run -e CI=true ksh931101/docker-react-app npm run test -- --coverage

after_success:
  -echo "Test success"